/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.eng.marcus.locadora.tela;

import br.eng.marcus.locadora.modelo.Carro;
import javax.swing.DefaultListModel;

/**
 *
 * @author Marcus Borges
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListCarrosDescricao = new javax.swing.JList<>();
        jButtonPrimeiraTela = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Escolha seu carro");

        jListCarrosDescricao.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListCarrosDescricao);

        jButtonPrimeiraTela.setBackground(new java.awt.Color(0, 153, 51));
        jButtonPrimeiraTela.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButtonPrimeiraTela.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPrimeiraTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/icon/icone.png"))); // NOI18N
        jButtonPrimeiraTela.setText("AVANÇAR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLabel1)
                .addContainerGap(125, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonPrimeiraTela))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPrimeiraTela)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }
   
    //criando os objetos com as suas propriedades 
    public void montaCatalogo(){
        Carro carro1 = new Carro();
        carro1.setAr(true);
        carro1.setCor(Carro.COR_PRETO);
        carro1.setKm(0);
        carro1.setMarca(Carro.MARCA_FIAT);
        carro1.setModelo(Carro.MODELO_FIAT_ARGO);
        carro1.setMotor("1.0 Flex");
        carro1.setPlaca("BRA-0001");
        carro1.setTipo(Carro.TIPO_HATCH);
        carro1.setValorDiaria(100.00);
        carro1.setValorcalcao(700.00);
        
        Carro carro2 = new Carro();
        carro2.setAr(true);
        carro2.setCor(Carro.COR_PRETO);
        carro2.setKm(0);
        carro2.setMarca(Carro.MARCA_FIAT);
        carro2.setModelo(Carro.MODELO_FIAT_TORO);
        carro2.setMotor("2.0 Diesel");
        carro2.setPlaca("PRQ-1098");
        carro2.setTipo(Carro.TIPO_CAMIONETE);
        carro2.setValorDiaria(160.00);
        carro2.setValorcalcao(1000.00);
        
        Carro carro3 = new Carro();
        carro3.setAr(true);
        carro3.setCor(Carro.COR_BRANCO);
        carro3.setKm(0);
        carro3.setMarca(Carro.MARCA_RENAULT);
        carro3.setModelo(Carro.MODELO_RENAULT_KWID);
        carro3.setMotor("1.0 Flex");
        carro3.setPlaca("PRQ-0001");
        carro3.setTipo(Carro.TIPO_HATCH);
        carro3.setValorDiaria(90.00);
        carro3.setValorcalcao(700.00);
        
        Carro carro4 = new Carro();
        carro4.setAr(true);
        carro4.setCor(Carro.COR_BRANCO);
        carro4.setKm(0);
        carro4.setMarca(Carro.MARCA_RENAULT);
        carro4.setModelo(Carro.MODELO_RENAULT_KANGOO);
        carro4.setMotor("1.6 Flex");
        carro4.setPlaca("PRQ-0061");
        carro4.setTipo(Carro.TIPO_ULTILITARIO);
        carro4.setValorDiaria(140.00);
        carro4.setValorcalcao(1000.00);
        
        Carro carro5 = new Carro();
        carro5.setAr(true);
        carro5.setCor(Carro.COR_PRATA);
        carro5.setKm(0);
        carro5.setMarca(Carro.MARCA_HYUNDAI);
        carro5.setModelo(Carro.MODELO_HYUNDAI_CRETA);
        carro5.setMotor("1.6 Flex");
        carro5.setPlaca("PRQ-0098");
        carro5.setTipo(Carro.TIPO_SUV);
        carro5.setValorDiaria(140.00);
        carro5.setValorcalcao(1000.00);
        
        Carro carro6 = new Carro();
        carro6.setAr(true);
        carro6.setCor(Carro.COR_PRATA);
        carro6.setKm(0);
        carro6.setMarca(Carro.MARCA_HYUNDAI);
        carro6.setModelo(Carro.MODELO_HYUNDAI_HB20);
        carro6.setMotor("1.0 TURBO FLEX");
        carro6.setPlaca("PRQ-0098");
        carro6.setTipo(Carro.TIPO_SUV);
        carro6.setValorDiaria(120.00);
        carro6.setValorcalcao(1000.00);
        
        //Agregando os bjetos em uma lista, 
        DefaultListModel<Carro> catalogo = new DefaultListModel<>();
        catalogo.addElement(carro1);
        catalogo.addElement(carro2);
        catalogo.addElement(carro3);
        catalogo.addElement(carro4);
        catalogo.addElement(carro5);
        catalogo.addElement(carro6);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPrimeiraTela;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jListCarrosDescricao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
